### ISSUE TITLE
WSL上でIntelコンパイラを用いてやねうら王のWindows用バイナリの生成する方法

### ISSUE THREAD

**Issue by mrt-tsk** [KazApps/YaneuraOu#2]
先日はありがとうございました。Intelコンパイラも導入してみました。
IntelコンパイラでAOCCコンパイラと同様の手順でビルドを行ったところ、前回のissueの冒頭で言われた通り、Unsupported PE target というエラーが出ました。解決策をご教授いただけないでしょうか。よろしくお願いします。

**Comment by mrt-tsk** [comment]
ちなみに実行環境についてですが
Intelコンパイラの導入方法については、https://qiita.com/tlasu/items/0f49c893e22fa646699dを参考にしました。
インストールしたのはintel-basekitのみです。
/opt/intel/oneapi/compiler/2024.2/bin/compiler/clang++ --versionコマンドで
Intel(R) oneAPI DPC++/C++ Compiler 2024.2.1 (2024.2.1.20240711)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/intel/oneapi/compiler/2024.2/bin/compilerのような出力です。

クロスコンパイルに必要なファイルは、/opt/intel/oneapi/compiler/2024.2/lib/clang/19/lib/windowsのようにコピーしました。
あとは、AOCCコンパイラの時と同様にまずは最低限の条件でビルドしてみました。
make clean tournament　COMPILER=/opt/intel/oneapi/compiler/2024.2/bin/compiler/clang++ EXTRA_CPPFLAGS="-stdlib=libc++ -target x86_64-w64-mingw32 -I/usr/include/mingw-w64 -static -pthread " EXTRA_LDFLAGS="-rtlib=compiler-rt -unwindlib=libunwind -L/usr/lib -L/mnt/c/msys64/mingw64/lib " -j 8

実行結果は
Unsupported PE target
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [Makefile:659: YaneuraOu-by-gcc] Error 1
make[1]: Leaving directory '/home/mrttsk/YaneuraOu/source'
make: *** [Makefile:693: tournament] Error 2
という感じです。

**Comment by KazApps** [comment]
気付くのが遅くなってしまい申し訳ありません。
それに関しては`Intel Compiler`に付属しているリンカではWindows用のバイナリは吐けないので、(あまり良いことではありませんが)msysの方のリンカを使うしかないです。
具体的には、
```bash
make clean tournament COMPILER=/opt/intel/oneapi/compiler/latest/bin/compiler/clang++ EXTRA_CPPFLAGS="-stdlib=libc++ -target x86_64-w64-mingw32 -I/usr/include/mingw-w64 -static -pthread" EXTRA_LDFLAGS="-rtlib=compiler-rt -unwindlib=libunwind -L/usr/lib -L/mnt/c/msys64/mingw64/lib" -j 8
```
のようなコマンドでコンパイルし、リンクエラーが出ると思いますが無視して、msysの方で
```bash
# WSL上でビルドしようとしているYaneuraOu/sourceに移動。WSLのUbuntu上のパスの場合、cd //wsl.localhost/Ubuntu-24.04/home/username/YaneuraOu/source のような感じで移動できる。
cd YaneuraOu/source
make tournament COMPILER=clang++ EXTRA_CPPFLAGS="-stdlib=libc++" EXTRA_LDFLAGS="-rtlib=compiler-rt -unwindlib=libunwind"
```
のような感じでビルドできます。重要なのは、`make clean tournament`ではなく、`make tournament`を使うことで、`Intel Compiler`でコンパイルしたファイルをリンクしてくれるようになります。
コンパイルオプション(CPUのアーキテクチャの指定)によっては、以下のようなリンカの警告が出ることもありますが、リンク自体は正しくできているようです(速度が落ちるかどうかとかは知りません)。
```bash
'-msrlist' is not a recognized feature for this target (ignoring feature)
'-pbndkb' is not a recognized feature for this target (ignoring feature)
'-wrmsrns' is not a recognized feature for this target (ignoring feature)
'-msrlist' is not a recognized feature for this target (ignoring feature)
'-pbndkb' is not a recognized feature for this target (ignoring feature)
'-wrmsrns' is not a recognized feature for this target (ignoring feature)
'-msrlist' is not a recognized feature for this target (ignoring feature)
'-pbndkb' is not a recognized feature for this target (ignoring feature)
'-wrmsrns' is not a recognized feature for this target (ignoring feature)
'-msrlist' is not a recognized feature for this target (ignoring feature)
'-pbndkb' is not a recognized feature for this target (ignoring feature)
'-wrmsrns' is not a recognized feature for this target (ignoring feature)
'-msrlist' is not a recognized feature for this target (ignoring feature)
'-pbndkb' is not a recognized feature for this target (ignoring feature)
'-wrmsrns' is not a recognized feature for this target (ignoring feature)
'-msrlist' is not a recognized feature for this target (ignoring feature)
'-pbndkb' is not a recognized feature for this target (ignoring feature)
'-wrmsrns' is not a recognized feature for this target (ignoring feature)
'-msrlist' is not a recognized feature for this target (ignoring feature)
'-pbndkb' is not a recognized feature for this target (ignoring feature)
'-wrmsrns' is not a recognized feature for this target (ignoring feature)
'-msrlist' is not a recognized feature for this target (ignoring feature)
'-pbndkb' is not a recognized feature for this target (ignoring feature)
'-wrmsrns' is not a recognized feature for this target (ignoring feature)
```

**Comment by KazApps** [comment]
そちらについてはあまり知らないのですが、[前回紹介したAMDのサイト](https://www.amd.com/content/dam/amd/en/documents/developer/version-4-2-documents/aocc/aocc-4.2-quick-reference-guide.pdf)に載っているオプションや[Intel公式のサイト](https://www.intel.com/content/www/us/en/docs/dpcpp-cpp-compiler/developer-guide-reference/2023-0/alphabetical-option-list.html)を参考にしてみてください。ビルドするマシンでパフォーマンスを最大限出したいのであれば、`clang`や`AOCC`でも同じですが、`-Ofast -march=native -mtune=native`あたりを付けておくと良いです(`-Ofast`は`Makefile`の方で指定されているのでわざわざ指定する必要はありませんが)。

**Comment by mrt-tsk** [comment]
なうほど！自分の使ってるCPUもZen4なので参考にさせていただきます。
ビルドするときに便利なのでまたMakefileに書き込もうと思います。
あ～そうでした。聞きたかったことがありました。
AVX512は最近動くようになったとプルリクかissueで見た覚えがあるのですが…現状公開されてるソースで反映はされてますか？

**Comment by mrt-tsk** [comment]
いままで動かないと聞いていたので、ちょっと気になってました。

**Comment by KazApps** [comment]
それに関してはまた別のIssueを開いてもらっていいですか? このIssueで他の話題をするのはあまり良くないと思うので。

**Comment by KazApps** [comment]
そしてビルドが完了したようなのでこのIssueは閉じさせていただきます。

**Comment by mrt-tsk** [comment]
そうですね。申し訳ありません。
全く違う話題ですし、またの機会に聞かせてください。
丁寧な対応をしていただき、ありがとうございました。

**Comment by mrt-tsk** [comment]
その後 https://github.com/yaneurao/YaneuraOu/pull/287 を参考にさせていただきヘッダーファイルを修正後、-DUSE_AVX512 -DUSE_BMI2 -DUSE_VNNI -march=native -mtune=nativeでビルドしたところ正常な動作を確認できました。
ありがとうございましたm(-_-)m
