### ISSUE TITLE
ペタショック定跡について

### ISSUE THREAD

**Issue by RedHotChickens** [KazApps/YaneuraOu#3]
エンジン設定等色々試した結果、自分の環境だと配布されている実行ファイルやmsysでビルドしたものについては無事に起動できたのですが、WSL上からWindows用にクロスコンパイルしたものに限って同じ設定をしても起動できませんでした。
ただ、すべての定跡ファイル(.db)が起動できないわけではなく、比較的軽い定跡ファイルは読み込めるという状況です。

ShogiGUIでやねうら王とふかうら王を使って検討しており、ふかうら王に定跡を搭載すれば起動できるので、研究環境としては問題ありませんが…検証のほどよろしくお願いいたします。

**Comment by RedHotChickens** [comment]
ペタショック定跡搭載時のデバックログの一部を貼ります。
```
>> setoption name GenerateAllLegalMoves value false
>> setoption name EnteringKingRule value CSARule27
>> setoption name ThreadIdOffset value 6
>> setoption name LargePageEnable value true
>> setoption name USI_OwnBook value true
>> setoption name NarrowBook value false
>> setoption name BookMoves value 256
>> setoption name BookIgnoreRate value 0
>> setoption name BookFile value user_book1.db
>> setoption name BookDir value book
>> setoption name BookEvalDiff value 30
>> setoption name BookEvalBlackLimit value 0
>> setoption name BookEvalWhiteLimit value -140
>> setoption name BookDepthLimit value 0
>> setoption name BookOnTheFly value true
>> setoption name ConsiderBookMoveCount value false
>> setoption name BookPvMoves value 8
>> setoption name IgnoreBookPly value true
>> setoption name FlippedBook value true
>> setoption name DrawValueBlack value -2
>> setoption name DrawValueWhite value -2
>> setoption name PvInterval value 300
>> setoption name ResignValue value 99999
>> setoption name ConsiderationMode value true
>> setoption name OutputFailLHPV value true
>> setoption name FV_SCALE value 20
>> isready
<< info string Hash table allocation: Windows Large Pages used.
<< info string EvalDirectory = C:\Users\User\Downloads\suisho10beta/eval
<< info string loading eval file : eval/nn.bin
<< info string USI_Hash : Start clearing with 26 threads , Hash size =  98304[MB]
<< info string USI_Hash : Finish clearing.
<< readyok
>> usinewgame
>> position sfen lnsgkgsnl/1r5b1/ppppppppp/9/9/7P1/PPPPPPP1P/1B5R1/LNSGKGSNL w - 2
>> go infinite
<< info depth 1 seldepth 2 score cp -47 multipv 1 nodes 3015 nps 1507500 hashfull 0 time 2 pv 8c8d
<< info depth 1 seldepth 2 score cp -58 multipv 2 nodes 3015 nps 1507500 hashfull 0 time 2 pv 4a3b 2f2e 8c8d 1g1f
<< info depth 1 seldepth 2 score cp -62 multipv 3 nodes 3015 nps 1507500 hashfull 0 time 2 pv 3c3d 2f2e 4a3b
<< info depth 2 seldepth 3 score cp -81 multipv 1 nodes 17314 nps 8657000 hashfull 0 time 2 pv 8c8d 7g7f 4a3b 1g1f 8d8e
<< info depth 2 seldepth 3 score cp -98 multipv 2 nodes 17314 nps 8657000 hashfull 0 time 2 pv 4a3b 7g7f 8c8d 1g1f 8d8e
<< info depth 2 seldepth 4 score cp -104 multipv 3 nodes 17314 nps 8657000 hashfull 0 time 2 pv 1c1d 2f2e 4a3b 2e2d 2c2d 2h2d
<< info depth 3 seldepth 4 score cp -40 multipv 1 nodes 25304 nps 12652000 hashfull 0 time 2 pv 8c8d 2f2e 8d8e 7g7f 4a3b 8h7g
```

**Comment by RedHotChickens** [comment]
他の定跡が動いた時のログです。
```
>> setoption name GenerateAllLegalMoves value false
>> setoption name EnteringKingRule value CSARule27
>> setoption name ThreadIdOffset value 6
>> setoption name LargePageEnable value true
>> setoption name USI_OwnBook value true
>> setoption name NarrowBook value false
>> setoption name BookMoves value 256
>> setoption name BookIgnoreRate value 0
>> setoption name BookFile value user_book3.db
>> setoption name BookDir value book
>> setoption name BookEvalDiff value 30
>> setoption name BookEvalBlackLimit value 0
>> setoption name BookEvalWhiteLimit value -140
>> setoption name BookDepthLimit value 0
>> setoption name BookOnTheFly value true
>> setoption name ConsiderBookMoveCount value false
>> setoption name BookPvMoves value 8
>> setoption name IgnoreBookPly value true
>> setoption name FlippedBook value true
>> setoption name DrawValueBlack value -2
>> setoption name DrawValueWhite value -2
>> setoption name PvInterval value 300
>> setoption name ResignValue value 99999
>> setoption name ConsiderationMode value true
>> setoption name OutputFailLHPV value true
>> setoption name FV_SCALE value 20
>> isready
<< info string Hash table allocation: Windows Large Pages used.
<< info string EvalDirectory = C:\Users\User\Downloads\suisho10beta/eval
<< info string loading eval file : eval/nn.bin
<< info string USI_Hash : Start clearing with 26 threads , Hash size =  98304[MB]
<< info string USI_Hash : Finish clearing.
<< readyok
>> usinewgame
>> position sfen lnsgkgsnl/1r5b1/ppppppppp/9/9/9/PPPPPPPPP/1B5R1/LNSGKGSNL b - 1
>> go infinite
<< info multipv 1 score cp 0 depth 32 pv 2g2f 8c8d 2f2e 8d8e 7g7f 1c1d 2e2d (100.00%)
<< info depth 0 seldepth 0 score cp 0 multipv 1 nodes 11 nps 687 hashfull 0 time 16 pv 2g2f 8c8d
<< info depth 1 seldepth 0 score cp 0 multipv 2 nodes 11 nps 687 hashfull 0 time 16 pv 1g1f
<< info depth 1 seldepth 0 score cp 0 multipv 3 nodes 11 nps 687 hashfull 0 time 16 pv 3g3f
>> stop
>> gameover draw
>> quit
<< bestmove 2g2f ponder 8c8d

```

**Comment by KazApps** [comment]
> WSL上からWindows用にクロスコンパイルしたものに限って同じ設定をしても起動できませんでした。

こちらの環境でも、`Intel(R) oneAPI DPC++/C++ Compiler 2025.0.1 (2025.0.1.20241113)`でクロスビルドした場合と、MSYS2の`clang 19`でビルドした場合に確認できました。`icx (Intel Compiler)` は `LLVM 19`をベースにしているため、`LLVM 19`由来のバグだと思われます。ただ、確証はないため、WSL上の`clang 18`でクロスビルドして試してみていただけると助かります。(MSYS2 の clang が version 18 なのであれば、そちらでビルドするのでも良いと思います)

**Comment by KazApps** [comment]
`MSYS2`の`clang`のバージョンを`18`にダウングレードしてみましたが同様の現象が発生しました。こちらの環境ではオプションに`-stdlib=libc++`を付けていて、そのオプションを削除すると正しく動作するようです。なので、LLVM 19のバグではなく、libc++のバグかもしれないです。

**Comment by RedHotChickens** [comment]
検証ありがとうございます。libc++のバグの可能性あるんですね。
後ほど該当オプションを削除してビルドしたものを実行してみようと思います。
MSYS2の`clang`バージョンは確認したところ、`18`でした。
ビルド時にも`-stdlib=libc++`のオプションをつけていたので、恐らく環境としては同条件だと思います。

**Comment by RedHotChickens** [comment]
WSL
`make clean tournament COMPILER=/opt/intel/oneapi/compiler/2024.2/bin/compiler/clang++ TARGET_CPU=ZEN4 YANEURAOU_EDITION=YANEURAOU_ENGINE_NNUE_HALFKP_512X2_8_64 ENGINE_NAME="YaneuraOu" EXTRA_CPPFLAGS="-target x86_64-w64-mingw32 -I/usr/include/mingw-w64 -static -pthread -DHASH_KEY_BITS=128 -DTT_CLUSTER_SIZE=4 -DEXCLUDED_MOVE_FORCE_EVALUATE -DENGINE_VERSION=\\\""V8.32DEV"\\\"" EXTRA_LDFLAGS="-rtlib=compiler-rt -unwindlib=libunwind -L/usr/lib -L/mnt/c/msys64/mingw64/lib" -j 8`
MSYS
`make tournament COMPILER=clang++ TARGET_CPU=ZEN4 YANEURAOU_EDITION=YANEURAOU_ENGINE_NNUE_HALFKP_512X2_8_64 ENGINE_NAME="YaneuraOu" EXTRA_CPPFLAGS="-DHASH_KEY_BITS=128 -DTT_CLUSTER_SIZE=4 -DEXCLUDED_MOVE_FORCE_EVALUATE -DENGINE_VERSION=\\\""V8.32DEV"\\\"" EXTRA_LDFLAGS="-rtlib=compiler-rt -unwindlib=libunwind"`

これでビルドしてみたのですが、エラーが出てしまいました。
`-stdlib=libc++`のみ削除したのですが、修正が足りない箇所ありますか？

**Comment by KazApps** [comment]
MSYSの方の原因はわかりませんが、
WSLの方は私も`-stdlib=libc++`を指定せずにクロスビルド成功したことないです。
MSYS、WSLのどちらもエラーメッセージを張り付けていただければ、対応できるかと思います。

**Comment by RedHotChickens** [comment]
libc++がないとリンカエラーが出てしまうので困っていました。
上記のコマンドは、WSLからクロスビルドしようとした時のです。それならこのコマンドではビルドできないはずですね。

MSYSで`make clean tournament COMPILER=clang++ TARGET_CPU=ZEN4 YANEURAOU_EDITION=YANEURAOU_ENGINE_NNUE_HALFKP_512X2_8_64 ENGINE_NAME="YaneuraOu" EXTRA_CPPFLAGS="-DHASH_KEY_BITS=128 -DTT_CLUSTER_SIZE=4 -DEXCLUDED_MOVE_FORCE_EVALUATE -DENGINE_VERSION=\\\""V8.32DEV"\\\"" EXTRA_LDFLAGS="-rtlib=compiler-rt -unwindlib=libunwind"`
このコマンドでビルドに成功し、ビルドしたバイナリで定跡も動作確認できました。
ありがとうございました！

**Comment by KazApps** [comment]
WSLの方で`-stdlib=libc++`を指定せずにクロスビルドできないか試してみましたが、難しいようです。
大きい定跡を使いたい場合には、NPSが多少落ちるかもしれませんが、MSYSで`stdlib=libc++`の指定なしてビルドするのが無難だと思います。

**Comment by RedHotChickens** [comment]
そちらも検証していただき、ありがとうございます。libc++なしでWSLのクロスビルドは難しいんですね。
ベンチマークを見る限り速度が大きく低下しているわけではなさそうで、わりと速い気もします。
大きな定跡を使う時は、今回ビルドしたバイナリをエンジン登録して使っていこうと思います。
